### ISSUE TITLE
Broken README

### ISSUE THREAD

**Issue by douira** [velikanov/opensource-candies#41]
It seems the formatting in the REAME.md file is messed up here a little: 
![screen shot 2018-09-24 at 21 12 20](https://user-images.githubusercontent.com/17120022/45973395-a0053000-c03e-11e8-88b5-4a758585861e.png)

**Comment by Croydon** [comment]
I do think that everything is fine there, this is a code snippet template for pull request, so that new list entries have all the same form.

**Comment by douira** [comment]
Oh ok I see. Btw GitHub automatically fills in PR and Issue templates if you provide template text files: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by velikanov** [comment]
@douira thank you!
will try this right away

**Comment by velikanov** [comment]
hm… however I don't think that PULL_REQUEST_TEMPLATE needs to be created - it doesn't provide the end user with any handy functionality…
all the way you need to write updates by hands :(
